### ISSUE TITLE
Editing Org files

### ISSUE THREAD

**Issue by manuel-uberti** [rolandwalker/hardhat#12]
Hi,

thanks for this great package. I have one minor issue: I cannot edit my Org files. I get this message when calling `hardhat-status`:
```
Hardhat marked this buffer protected, because: function test matched "hardhat-protected-by-ignoramus"
```
Is there some setting I missed?

The files I cannot edit are in `~/org`. However, I can edit the files in all the subdirectories (i.e. `~/org/papers`). Also, `ignoramus` is not ignoring those files, meaning I can see them in Dired for instance.

**Comment by manuel-uberti** [comment]
Debugging a little further, I found out that this code:
```
(ignoramus-boring-p (hardhat-safe-file-truename (expand-file-name "~/org/organizer.org")))
```
Returns: 
```
("/home/manuel/org/organizer.org" completepath "/home/manuel/.emacs.d/abbrev_defs" "/home/manuel/org/organizer.org")

So `hardhat-protected-by-ignoramus` returns a non-nil value.
```
IIUC,

**Comment by manuel-uberti** [comment]
I did a bit more debugging. Trying this code:
```
(let ((case-fold-search ignoramus-case-insensitive)
      (file (hardhat-safe-file-truename (expand-file-name "~/org/organizer.org"))))
  (and ignoramus-use-known-datafiles
       (ignoramus-matches-datafile file)))
```
I nailed it down to `ignoramus-matches-datafile`. Unfortunately, my Elisp knowledge doesn't go much further than this.

**Comment by manuel-uberti** [comment]
Ok, forget the issue, this fixed it:
```
(add-to-list 'hardhat-fullpath-editable-regexps "~/org")
```
:)

**Comment by rolandwalker** [comment]
Very helpful.  I found one bug already which affects reporting.

What is the value of variable `org-default-notes-file` in your setup?  I don't use org-mode myself, and maybe that file should not be treated as uneditable.

**Comment by manuel-uberti** [comment]
I've got this in my setup:
```
(setq org-directory (expand-file-name "~/org/")
        org-default-notes-file
        (expand-file-name "organizer.org" org-directory))
```

**Comment by rolandwalker** [comment]
Many thanks!

Ignoramus.el had assumed that the file named in variable `org-default-notes-file` was only edited programmatically (and never by hand).  But as I said I am not an org-mode user, so I disabled that, and pushed new releases of ignoramus and hardhat to MELPA.

**Comment by manuel-uberti** [comment]
Thank you for the fix. That means I can remove this
```
(add-to-list 'hardhat-fullpath-editable-regexps "~/org")
```
from my config, right?

**Comment by manuel-uberti** [comment]
Yes, it works. Thank you again!
